language: node_js
node_js:
  - "node"
sudo: required
services:
  - docker
before_install:
  - docker build -t docker-ci-aws .
script:
  - echo "After success"
  - npm run test
    # 使用 curl 測試 docker 是否有順利執行 node
  - docker run -d -p 3000:3000 docker-ci-aws; sleep 10
  - curl --retry 10 --retry-delay 5 -v http://localhost:3000
  - echo "Finish..."

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-1"  
  app: "new-try"
  env: "NewTry-env"
  bucket_name: "elasticbeanstalk-us-east-1-885661614159"
  bucket_path: "docker"
  on:
    branch: master